# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nlZ4vG8W1TxyOdDJWRjUeMnheeTIUFmU
"""

import pandas as pd
baza={
    "fish":[  "qadanova Zulayho ","Xalilov Durbek "    ],
      "fan nomi": [   "suniy intelekt " , "suniy intelekt "   ],
      "mashg'ulot turi" :[ "amaliy mashgulot" ,"maruza"   ],
    "kafedrasi ":["axbarot texnologyalari ", "axbarot texnologyalari" ],
}
dp=pd.DataFrame (baza)
print ( dp)

import pandas as pd
baza={
    "fish":[  "qadanova Zulayho ","Xalilov Durbek " ,"Abdullayeva Moxigul ","Xontorayev Sardorbek ","Turdimatov Mamirjon ","Araboyev Alisher " ,"Jurayeva Gulnozaxon" ],
      "fan nomi": [   "suniy intelekt " , "suniy intelekt " ,"Malumotlar tuzilmasi " ,"Malumotlar tuzilmasi ","kiber hafsizlik ", "kiber hafsizlik" ,"ELEKTRON SXEMA"],
      "mashg'ulot turi" :[ "amaliy mashgulot" ,"maruza","amaliy ", "maruza", "amaliy ", "amaliy ","amaliy "  ],
    "kafedrasi ":["axbarot texnologyalari ", "axbarot texnologyalari" ,"TABIY FANLAR","axbarot texnologyalari","axbarot texnologyalari","axbarot texnologyalari","KISIF"],
}
dp=pd.DataFrame (baza)
print ( dp)

dp.to_excel("teachers.xlsx")